### ISSUE TITLE
Poor name choice

### ISSUE THREAD

**Issue by haarg** [perlancar/perl-PERLANCAR-List-Util-PP#1]
List::Util::PP is a module that used to be part of Scalar-List-Utils dist, providing PP variants of the functions.  Having the dist be XS-optional caused a number of issues though, so eventually the XS portion was made mandatory, and the PP code was dropped.  List::Util::PP was still included with perl until 5.16.  List::Util::PP is also still reserved in PAUSE to the authors of Scalar-List-Utils.  It's also possible that List::Util::PP will come back in some form in the future as part of List::Util proper.

So there are a few reasons why List::Util::PP is a poor choice for a name for this module.  I don't have a specific suggestion for what you should use instead.

Separate from the naming, I worked on creating a complete List::Util::PP module to go along with some potential packaging changes in Scalar-List-Utils.  That work has stalled, but the code is [here](https://github.com/haarg/List-Util/blob/pp/lib/List/Util/PP.pm) and may be useful to you.

**Comment by karenetheridge** [comment]
You wouldn't be able to release this module under this name anyway, since PAUSE permissions are held by GBARR and PEVANS.

**Comment by perlancar** [comment]
My bad, didn't check beyond normal CPAN search before releasing. I'll move
to PERLANCAR-List-Util-PP.
